### Numpy

In [2]:
import numpy as np

## create array using numpy
## create a 1D array

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) ## 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [4]:
arr2.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [8]:
## 2-D array

arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [11]:
## Create array using inbuilt function

arr3= np.arange(0,10,2)
arr3.reshape(1,5)
arr3.reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
## identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
## Attributes in Numpy

arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n", arr)
print("Shape:",arr.shape)
print("Number of dimensions:",arr.ndim)
print("Size (number of elements):", arr.size)
print("Data Type:", arr.dtype)
print("Item size (in Bytes):",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data Type: int64
Item size (in Bytes): 8


In [19]:
### Numpy Vectorized Operation

arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])


### Element Wise addition
print("Addition:",arr1+arr2)

### Element Wise Substraction
print("Substraction:",arr1-arr2)

### Element Wise Multiply
print("Multiply:",arr1*arr2)

### Element Wise Division
print("Division:",arr1/arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiply: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [23]:
### Universal Function

arr=np.array([2,3,4,5,6])

## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [24]:
## Universal Function(ufunc)
## array slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print("Array:", arr)

Array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
arr[0][1]

np.int64(2)

In [26]:
arr[2][2]

np.int64(11)

In [27]:
arr[2:]

array([[ 9, 10, 11, 12]])

In [28]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [30]:
arr[0:2,1:]

array([[2, 3, 4],
       [6, 7, 8]])

In [32]:
## Modify array Element

arr[0][0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [33]:
### statistical concepts--normalization
### to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

# calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) /std_dev
print("Normalized data:", normalized_data)


Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [36]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

## Mean
mean = np.mean(data)
print("Mean:", mean)

## Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:",variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [42]:
## Logical Operation

data = np.array([1,2,3,4,5,6])

print(data[data>3])

data[data<4]

data[ (data>2) & (data<4) ]


[4 5 6]


array([3])